---
title: "About The Project"
description: |
  Details and Citations
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## *Citations*

### *Data Collection*

*Allan, Alex; Grateful Dead Lyric & Song Finder: https://whitegum.com/~acsa/intro.htm*

*ASCAP. 18 March 2022.*

*Dodd, David; The Annotated Grateful Dead Lyrics: http://artsites.ucsc.edu/gdead/agdl/*

*Schofield, Matt; The Grateful Dead Family Discography: http://www.deaddisc.com/*

*This information is intended for private research only, and not for any commercial use. Original Grateful Dead songs are ©copyright Ice Nine Music*

### *Bibliography*

Gallo, P. (2001, Sep). What a long, rich trip it's been. Variety, 384, 22. http://silk.library.umass.edu/login?url=https://www.proquest.com/magazines/what-long-rich-trip-been/docview/236301825/se-2?accountid=14572

For the first time, the Dead's recordings are being used as the barometers of how good the band once was. The group's "American Beauty," "Europe '72" and "In the Dark" are its only discs to top 2 million in sales. Instead, the Dead were known to dominate the touring world: They were the highest-grossing act of 1993 pulling in $45.6 million, and $52.4 million in 1994.

Meriwether, N. G. (Ed.). (2012). Reading the grateful dead : A critical survey. Scarecrow Press.

So the Deadheads did something really fascinating. In the absence of ordained dogma coming down ex cathedra, they glommed on to song order: a set of phenomena— just phenomena, like baseball statistics. I don’t know why. We didn’t know our own song orders, I swear to God! And maybe that was the reason: The Deadheads did. I swear, sometimes Deadheads actually controlled the set list far more than they knew, just because they believed that something else was going to happen next, and the band said, “Oh well, what do you want to play? Oh, OK.” Somehow that would be transmitted from the Deadheads, and maybe that’s why they thought that was where the holiness was. (Barlow, p 33)


Of course, for fans, it has always been the live performances of these songs that made them resonate so deeply. As one early academic researcher asserted, “One cannot learn ‘to do Dead’ from the tapes, however. Actual initiation must occur in the concert environment” (Pearson, thesis 20). Though this charge has been leveled by earlier generations of critics addressing other musical genres, and while some Deadheads— especially those in foreign countries— might disagree, all Deadheads would agree that live performances were the raison d’être of the band. 14 Over the course of thirty years, the Dead played more than 2,300 concerts for an audience estimated at twenty-five million, possibly the largest of any band in American history. 15 What is important about those statistics is what they conceal: The Dead never played the same show twice. Throughout their career, the goal was to court the muse of collective improvisation and see where she led; this lay at the heart of why fans went to show after show, year after year. 16 It also explains a large part of the appeal of studying the Dead— and it certainly explains the central artifact in Dead studies, the concert recordings. Early in the band’s career, band members recognized the importance of taping their performances: They listened to them after the gigs in order to improve, and to mine them for especially evocative phrases and passages for later use in new compositions. 17 Fans wanted to remember, too, and began making their own tapes very early in the band’s career. 18 That practice mushroomed over the years and created an immense body of evidence that now makes possible a great deal of work. As one scholar commented, “As tapes represent one of the few artifacts recoverable from the concert experience, they can be considered a source of ‘hard data’ in the research enterprise” (Pearson, “Ethnomethodology” 429). Between the band’s own voluminous archive of concert recordings, the source of more than a hundred releases to date, and the many, many thousands of live tapes made by fans, the number of recordings available to researchers is remarkable. 19 A higher percentage of the Rolling Stones’ performances may have been recorded— but the oeuvre of the Dead, the number of performances they played, and, most of all, the variations in set list and performance are far greater. In academic terms, no other rock band is so well documented— and no other rock band’s music and approach to performance merits such attention. (Meriwether, p 40)


I believe that the Grateful Dead’s music is actually part of a lifeworld created by active listeners. This lifeworld is learned, either from hearing Grateful Dead music on numerous occasions, or from being open to hear the music in a certain way” (Ganter 176). Band members said as much in interviews over the years. Garcia stated unequivocally that he’d “never experienced the click of great music without an audience. . . . We exist by their grace” (McNally, A Long Strange Trip 389). Even normally taciturn drummer Bill Kreutzmann told band biographer Dennis McNally that “when it’s really happening, the audience is as much a part of the band as the band is the audience. There is no difference. The audience should be paid— they contribute as much” (389). Not surprisingly, the most vivid description was written by lyricist Robert Hunter, in a long public letter: When the Dead are playing their best, blood drips from the ceiling in great, rich drops. Together we do a kind of suicide in music which requires from each of us just enough information short of dropping the body to inquire into those spaces from which come our questions. It is partly about how living might occur in the shadow of certain death; that death is satisfactory or unsatisfactory according to how we’ve lived and what we yield. The contemplation of death for the unfulfilled is a nightmare, and it is good that it should be. The vision of life without a great deal of responsibility is hollow. Satisfaction in itself is nothing to be sought, it’s simply an excretion of the acceptance of responsibility. (“Robert Hunter, Dark Star” 53) (Meriwether, p 44)




